apiVersion: v1
kind: Service
metadata:
  name: my-bulkmail-service
spec:
  type: NodePort
  selector:
    app: mymail
  ports:
    - port: 5000         # Cluster IP port
      targetPort: 5000   # Pod container port
      nodePort: 31564
